In [1]:
import numpy as np

In [3]:
from sklearn.preprocessing import MinMaxScaler

In [5]:
data = np.random.randint(0, 100, (10, 2))

In [6]:
data

array([[61, 85],
       [43, 55],
       [73, 71],
       [75, 19],
       [55, 98],
       [61, 30],
       [30, 55],
       [53,  9],
       [77, 43],
       [55,  3]])

In [8]:
# saber o valor minino e maximo do modelo
scaler_model = MinMaxScaler()

In [9]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [10]:
scaler_model.fit(data)

/home/paula/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [11]:
scaler_model.transform(data)

array([[ 0.65957447,  0.86315789],
       [ 0.27659574,  0.54736842],
       [ 0.91489362,  0.71578947],
       [ 0.95744681,  0.16842105],
       [ 0.53191489,  1.        ],
       [ 0.65957447,  0.28421053],
       [ 0.        ,  0.54736842],
       [ 0.4893617 ,  0.06315789],
       [ 1.        ,  0.42105263],
       [ 0.53191489,  0.        ]])

In [13]:
import pandas as pd

mydata = np.random.randint(0, 101, (50, 4))

In [15]:
mydata

array([[  5,  66,  93,   1],
       [ 92,  68,   7,  47],
       [100,  48,   2,  65],
       [ 90,  86,  92,  20],
       [ 56,  19,  80,  23],
       [ 29,   7,  48,  44],
       [ 70,   9,   5,  45],
       [ 94,   6,  27,   7],
       [ 74,   1,   9,  12],
       [ 83,  94,  11,  51],
       [ 52,  25,  24,  12],
       [ 11,  86,  90,   3],
       [ 74,  95,  67,  26],
       [  3,  52,  36,  92],
       [ 58,  82, 100,  94],
       [ 90,   1,  92,  45],
       [ 88,  83,  12,  77],
       [ 23,  81,  51,  95],
       [ 45,  93,  13,  37],
       [ 12,  44,   9,  99],
       [  4,  51,  25,  47],
       [ 41,  85,  92,   3],
       [ 11,  85,  76,  99],
       [ 63,  47,  62,  28],
       [ 13,  36,  49,   9],
       [ 74,   2,  19,  93],
       [ 67,  39,  19, 100],
       [ 33,  94,  89,  11],
       [ 67,  41,  89,  25],
       [  0,  52,  90,  66],
       [ 76,  39,  44,  43],
       [ 20,  34,  54,  91],
       [  5,  34,  10,  88],
       [ 19,  52,  75,  55],
       [ 85,  

In [18]:
data = pd.DataFrame(data=mydata, columns= ['f1', 'f2', 'f3', 'label'])

In [19]:
data

f1  f2   f3  label
0     5  66   93      1
1    92  68    7     47
2   100  48    2     65
3    90  86   92     20
4    56  19   80     23
5    29   7   48     44
6    70   9    5     45
7    94   6   27      7
8    74   1    9     12
9    83  94   11     51
10   52  25   24     12
11   11  86   90      3
12   74  95   67     26
13    3  52   36     92
14   58  82  100     94
15   90   1   92     45
16   88  83   12     77
17   23  81   51     95
18   45  93   13     37
19   12  44    9     99
20    4  51   25     47
21   41  85   92      3
22   11  85   76     99
23   63  47   62     28
24   13  36   49      9
25   74   2   19     93
26   67  39   19    100
27   33  94   89     11
28   67  41   89     25
29    0  52   90     66
30   76  39   44     43
31   20  34   54     91
32    5  34   10     88
33   19  52   75     55
34   85  19   55      2
35   52  76   24     93
36   56   7   34     75
37   49  66    2     50
38   32  89   60     24
39   50  63   91     95
40   85  51   46     79
41   41  10   78     82
42   85  25   17     56
43   18   8    5     99
44   39  20   37      9
45   99   4   65     90
46   31  32   70      6
47   14   6   16     26
48   30  43   22     47
49   79   8   22     67

In [20]:
x = data[['f1', 'f2', 'f3']]

In [22]:
y = data['label']

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=101)

In [25]:
x_train.shape

(35, 3)

In [26]:
x_test.shape

(15, 3)

In [27]:
y_train.shape

(35,)

In [28]:
y_test.shape

(15,)